name: Tests on github (update db.json and create results.md)

on:
  workflow_dispatch:
  # schedule:
  #   # every day at 3:00 AM
  #   - cron:  '0 3 * * *'
  # push:
  #   branches:
  #     - master
      
jobs:
  
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: test make help
        run: |
          pip install g4f -U
          chmod +x main.py
          ./main.py 

      - name: Commit results
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github
          author_email: mail@example.com
          message: 'update results from github'
          add: |
            - results.md
            - db.json